export default {
  welcome: "Welcome",
  signIn: "Sign In",
  signUp: "Sign Up",
  dontHaveAccount: "Don’t have an account?",
  haveAccount: "Do you have an account?",
  password: "Password",
  phoneNumber: "Mobile Number",
  reset: "Reset",
  proceed: "Proceed",
  forgotPasswordLabel: "Forgot your password?",
  clickReset: "Click here to reset",
  resetPassword: "Reset password",
  passwordUpdated: "Password updated",
  enterPhoneNumberLabel:
    "Enter your Mobile Phone Number. We will send  SMS to your verify it.",
  enterSmsCodeLabel:
    "Please enter the SMS code we sent to verify your phone number.",
  errorIncorrectPassword: "Incorrect password",
  passwordsDoNotMatch: "Passwords do not match",
  errorIncorrectPhoneNumber: "Incorrect phone number",
  gotIt: "Got it",
  sendSMSMessage:
    "We will send you an SMS message to verify your phone number.",
  proceedSecurely: "Proceed Securely",
  selectBrand: "Select Your Brand",
  search: "Search",
  select: "Select",
  myself: "Myself",
  someoneElse: "Someone Else",
  tellAboutYourself: "To get started, please tell us a bit about yourself",
  willBeAskedLater:
    "If you are enrolling on behalf of a patient, you will be asked for their information a little later.",
  firstName: "First Name",
  lastName: "Last Name",
  email: "Email",
  dateOfBirth: "Date of Birth",
  mustBeOlder: "User must be 19 years of age or older.",
  saveAndProceed: "Save & Proceed",
  errorIncorrectEmail: "Incorrect e-mail",
  errorIncorrectFirstName: "First name too long",
  errorIncorrectLastName: "Last Name too long",
  youCreatingAccountFor:
    "Are you creating this account for yourself or for someone else?",
  selectAndProceed: "Select & Proceed",
  ageModalTitle: "This app is available for users 19 years of age and above.",
  ageModalDescription:
    "Please have a parent or caregiver complete your enrollment or call the program at 1-888-304-2034 for assistance.",
  understood: "Understood",
  cancel: "Cancel",
  confirmDate: "Confirm Date",
  tellAboutPatient: "Please tell us about the patient",
  yourRelationship: "Your Relationship to the patient",
  spouse: "Spouse",
  parent: "Parent",
  child: "Child",
  careGiver: "Caregiver",
  almostDone: "Almost Done",
  weNeedBitMoreInformation:
    "We need a bit more information to complete your enrollment.",
  gender: "Gender",
  male: "Male",
  female: "Female",
  other: "Other",
  doctorsName: "Doctor's Name",
  enterNameOfTheDoctor: "Please enter the name of the doctor that prescribed ",
  selectYourProvince: "Select Your Province",
  verify: "Verify",
  confirmPhoneNumber: "Confirm Your Phone Number",
  enterSMS: "Please enter the SMS code we sent to verify your phone number.",
  smsCode: "SMS Code",
  resend: "Resend",
  change: "Change",
  save: "Save",
  changePhoneNumber: "Change Phone Number",
  createYourPassword: "Create Your Password",
  passwordShouldBe: "Password should be at least 8 characters long.",
  createPassword: "Create Password",
  confirmPassword: "Confirm Password",
  agreeToTermOfUse: "I agree to the",
  termOfUse: "Terms of Use",
  andReadThe: "and have read the",
  privacyPolicy: "Privacy Policy",
  savePassword: "Save Password",
  continue: "Continue",
  about: "About",
  healthCard: "Health Card",
  insurance: "Insurance",
  address: "Address",
  yourAddress: "Your address",
  primaryAddress: "Primary address",
  selectYourPrimaryAddress: "Select your primary address",
  addAddress: "Add address",
  editAddress: "Edit address",
  addressType: "Address type",
  street: "Street",
  city: "City",
  province: "Province",
  postalCode: "Postal code",
  home: "Home",
  work: "Work",
  primary: "Primary",
  update: "Update",
  prescription: "Prescription",
  financialAssistance: "Financial Assistance",
  program: "Program",
  logOut: "Log Out",
  addPrescription: "Add Prescription",
  ifYouHaveCopy: "If you have a copy of your ",
  pleaseUploadIt: "® prescription please upload it here.",
  skip: "Skip",
  addImage: "Add Image",
  addAnotherImage: "Add Another Image",
  uploadPrescription: "Upload Prescriptions",
  uploadPrescriptionReceipt: "Upload prescription receipt",
  takePhoto: "Take Photo",
  uploadFromPhone: "Upload From Phone",
  viewPrescription: "View Prescription",
  addDispenses: "Add dispenses",
  takePicture: "Take a picture of your prescription receipt.",
  healthCardTitle: "Your Provincial Health Card",
  uploadImages: "Please upload front and back images of your health card.",
  front: "Front",
  back: "Back",
  addImageFront: "Add Image\n(Front)",
  addImageBack: "Add Image\n(Back)",
  addInsurer: "Add Insurer",
  uploadCopyInsurance:
    "If you have a copy of your Insurance Card, please upload it here.",
  primaryInsurance: "Primary Insurance",
  secondaryInsurance: "Secondary Insurance",
  addSecondaryInsurance: "Add Secondary Insurance",
  scheduleFirstCall: "Schedule Your First Phone Call",
  letUsNowAboutTime:
    "Our team is here to help. Let us know when would be your preferred time to speak with one of our Case Managers.",
  currentDay: "Current\nBusiness Day",
  nextDay: "Next\nBusiness Day",
  morning: "Morning",
  afternoon: "Afternoon",
  evening: "Evening",
  finish: "Finish!",
  viewingAs: "Viewing As",
  welcomeTo: "Welcome to",
  whatWouldYouLikeToDo: "What would  you like to do?",
  visit: "Visit",
  toAccessMoreResources: "to access more patient resources",
  financialAssist: "Financial assist",
  addMembers: "Add a Member",
  settings: "Settings",
  help: "Help",
  call: "Call",
  weAreHereToHelp: "Questions? We are here to help",
  switchTo: "Switch To",
  profile: "Profile",
  language: "Language",
  english: "English",
  french: "French",
  account: "Account",
  security: "Security",
  changePassword: "Change Password",
  updateSettings: "Update Settings",
  enterPasswordToVerify: "Please enter the password to verify your account.",
  enterYourPassword: "Enter Your Password",
  confirmAndProceed: "Confirm and Proceed",
  createNewPassword: "Create New Password",
  makePasswordLonger:
    "Long passwords are stronger, so make your password at least 8 characters long.",
  confirmNewPassword: "Confirm New Password",
  successfullyChangedPassword: "You have successfully changed your password",
  backToSettings: "Back to Settings",
  backToHome: "Back to Home",
  yourPassword: "Your Password",
  newMobilePhone: "New Mobile Phone",
  enterPasswordAndNewPhone:
    "Please enter the password to verify your account. Then enter a new phone number. We will send you an SMS message to verify your mobile number.",
  verifyNewMobilePhone: "Verify New Mobile Number",
  codeHasBeenSent: "An 4-digit code has been sent to:",
  mobileNumberHasBeenChanged: "Mobile number has been changed",
  youSuccessfullyChangedTo:
    "You have successfully changed your account number to",
  cameraPermission: '"Luminav" Camera Permission',
  needAccessToCamera: '"Luminav" needs access to your camera',
  prescriberName: "Prescriber Name",
  yourPrescriptions: "Your Prescriptions",
  yourInsuranceDetails: "Your Insurance Details",
  addOrDeletePrescriptions: "Add or delete a picture of your prescription.",
  whoWouldYouLikeAdd: "Who would you like to add?",
  weNeedMoreInfoAboutMember:
    "We need a bit more information to complete  enrollment of the member.",
  selectProvince: "Select a Province",
  uploadHealthCard: "Upload Provincial Health Card",
  provincialHealthCard: "Provincial Health Card",
  uploadInsurances: "Upload Insurances",
  dispenses: "Dispenses",
  passwordMustContain:
    "The password must contain three out of four of the following:",
  requirementsToPassword:
    "* Lowercase character;\n* Uppercase character;\n* Numbers (0-9);\n* Symbols (@ # $ % ^ & * - _ ! + = [ ] { }  | : ‘ , . ? / ` ~ “ ( ) ;)"
};
